import type { Candidate } from "./model";
const updated = "2026-10-04";
const image = (id: string) => `/assets/${id}.webp`;
export const candidates: Candidate[] = [
  {
    id: "chiang",
    name: "蔣萬安",
    county: "臺北市",
    district: "臺北市",
    office: "metro-mayor",
    party: "中國國民黨",
    status: "registered",
    candidacySource: "https://www.cna.com.tw/news/aipl/202609040292.aspx",
    nicknames: [{ name: "巨蛋開箱王", kind: "creative" }],
    news: {
      title: "大巨蛋交流賽首度滿場",
      summary:
        "2024 年讀賣巨人交流賽讓大巨蛋首度滿場；蔣萬安表示要求改善現場缺失。",
      url: "https://www.cna.com.tw/news/aloc/202403040068.aspx",
      date: "2024-03-04",
    },
    meme: "別人的蛋用煎的，我的蛋坐滿的。",
    color: "#000095",
    image: image("chiang"),
    updated,
  },
  {
    id: "shen",
    name: "沈伯洋",
    county: "臺北市",
    district: "臺北市",
    office: "metro-mayor",
    party: "民主進步黨",
    status: "registered",
    candidacySource: "https://www.cna.com.tw/news/aipl/202609040292.aspx",
    nicknames: [
      {
        name: "Puma",
        kind: "public",
        source: "https://www.youtube.com/watch?v=ND3IbAz7nkI",
      },
    ],
    news: {
      title: "黑熊學院舉辦全民防衛課程",
      summary: "沈伯洋共同發起黑熊學院，推廣民防與基礎救護等訓練。",
      url: "https://www.rti.org.tw/news/view/id/2144818",
      date: "2022-09-18",
    },
    meme: "出門帶鑰匙、錢包，還有一隻熊。",
    color: "#009900",
    image: image("shen"),
    updated,
  },
  {
    id: "miao",
    name: "苗博雅",
    county: "臺北市",
    district: "大安區、文山區",
    office: "metro-council",
    party: "社會民主黨",
    status: "registered",
    candidacySource: "https://news.tvbs.com.tw/politics/4017756",
    nicknames: [{ name: "登記搭檔", kind: "creative" }],
    news: {
      title: "與林亮君聯合登記參選",
      summary:
        "2026 年 9 月，苗博雅與林亮君一同登記爭取議員連任；「我們登記了」貼文引起討論。",
      url: "https://www.ftvnews.com.tw/news/detail/2026902W0627",
      date: "2026-09-02",
    },
    meme: "我們登記了！……選舉的那種。",
    color: "#e980ac",
    image: image("miao"),
    updated,
  },
  {
    id: "lee",
    name: "李四川",
    county: "新北市",
    district: "新北市",
    office: "metro-mayor",
    party: "中國國民黨",
    status: "registered",
    candidacySource: "https://www.cna.com.tw/news/aipl/202609040312.aspx",
    nicknames: [
      {
        name: "川伯",
        kind: "public",
        source: "https://www.cna.com.tw/news/aloc/202604070334.aspx",
      },
    ],
    news: {
      title: "新北藍白合民調勝出",
      summary: "2026 年新北市藍白協調民調由李四川勝出，黃國昌表示全力輔選。",
      url: "https://news.pts.org.tw/article/805755",
      date: "2026",
    },
    meme: "這一關的對手，竟然是我自己。",
    color: "#000095",
    image: image("lee"),
    updated,
  },
  {
    id: "su",
    name: "蘇巧慧",
    county: "新北市",
    district: "新北市",
    office: "metro-mayor",
    party: "民主進步黨",
    status: "registered",
    candidacySource: "https://www.cna.com.tw/news/aipl/202609040312.aspx",
    nicknames: [
      {
        name: "水獺媽媽",
        kind: "public",
        source: "https://chiao.tw/ottermama",
      },
    ],
    news: {
      title: "水獺媽媽持續說故事",
      summary:
        "蘇巧慧經營「水獺媽媽巧巧話」Podcast，以繪本故事與台語小教室陪伴親子。",
      url: "https://chiao.tw/ottermama",
      date: "2026",
    },
    meme: "別急，選舉前先聽一個睡前故事。",
    color: "#009900",
    image: image("su"),
    updated,
  },
  {
    id: "chen",
    name: "陳紫渝",
    county: "新北市",
    district: "永和區永福里",
    office: "village",
    party: "無黨籍",
    status: "registered",
    candidacySource: "https://www.youtube.com/watch?v=M4RvNhsJq5I",
    nicknames: [
      {
        name: "最美里長",
        kind: "public",
        source: "https://www.youtube.com/watch?v=M4RvNhsJq5I",
      },
    ],
    news: {
      title: "曬出登記照、爭取里長連任",
      summary: "2026 年 9 月陳紫渝公布參選登記照片，爭取永福里里長連任。",
      url: "https://www.youtube.com/watch?v=M4RvNhsJq5I",
      date: "2026-09-07",
    },
    meme: "里民服務中，出息值也服務一下。",
    color: "#9a72d8",
    image: image("chen"),
    updated,
  },
  {
    id: "zhou",
    name: "周至剛",
    county: "新北市",
    district: "烏來區",
    office: "indigenous-mayor",
    party: "無黨籍",
    status: "reported",
    candidacySource: "https://udn.com/news/story/124652/9766917",
    nicknames: [{ name: "溫泉隊長", kind: "creative" }],
    news: {
      title: "山豬阿烏領隊烏來小旅行",
      summary:
        "烏來推出溫泉漫遊小旅行，由吉祥物山豬阿烏帶路；區長周至剛出席啟動活動。",
      url: "https://news.ipcf.org.tw/202189",
      date: "2026-05-18",
    },
    meme: "泡湯可以，出息可不能泡湯。",
    color: "#da9f48",
    image: image("zhou"),
    updated,
  },
  {
    id: "hsu",
    name: "許淑華",
    county: "南投縣",
    district: "南投縣",
    office: "county-mayor",
    party: "中國國民黨",
    status: "registered",
    candidacySource: "https://www.cna.com.tw/news/aipl/202609020170.aspx",
    nicknames: [
      {
        name: "神力女超人",
        kind: "public",
        source: "https://www.youtube.com/watch?v=9S31hTDUM-Y",
      },
    ],
    news: {
      title: "曾以神力女超人造型主持活動",
      summary:
        "許淑華的神力女超人造型曾引起討論；2026 年已登記爭取南投縣長連任。",
      url: "https://www.youtube.com/watch?v=9S31hTDUM-Y",
      date: "2018-12-10",
    },
    meme: "披風穿好了，今天也要跑十三鄉鎮。",
    color: "#000095",
    image: image("hsu"),
    updated,
  },
  {
    id: "zhong",
    name: "鍾孟儒",
    county: "苗栗縣",
    district: "頭份市、三灣鄉、南庄鄉",
    office: "county-council",
    party: "無黨籍",
    status: "reported",
    candidacySource: "https://sport.ftvnews.com.tw/news/detail/2026925W0271",
    nicknames: [
      {
        name: "美女里長",
        kind: "public",
        source: "https://finance.ftvnews.com.tw/news/detail/2026721C04M1",
      },
    ],
    news: {
      title: "徵助理貼文引網友歪樓",
      summary:
        "文化里里長鍾孟儒徵選務助理的貼文引起討論；後續 9 月報導已稱她為縣議員參選人。",
      url: "https://finance.ftvnews.com.tw/news/detail/2026721C04M1",
      date: "2026-07-21",
    },
    meme: "我在徵助理，你們在填戀愛履歷？",
    color: "#d478a3",
    image: image("zhong"),
    updated,
  },
  {
    id: "chou",
    name: "周佳琪",
    county: "屏東縣",
    district: "屏東市",
    office: "town-mayor",
    party: "中國國民黨",
    status: "registered",
    candidacySource: "https://udn.com/news/story/124652/9735138",
    nicknames: [{ name: "築夢隊長", kind: "creative" }],
    news: {
      title: "屏東市長選戰雙姝對決",
      summary: "周佳琪登記競選連任，與民進黨梁育慈競逐屏東市長。",
      url: "https://udn.com/news/story/124652/9735138",
      date: "2026-09-04",
    },
    meme: "夢可以很大，鬧鐘還是要設。",
    color: "#000095",
    image: image("chou"),
    updated,
  },
  {
    id: "lin",
    name: "林瑞德",
    county: "新竹縣",
    district: "竹北市第一選區",
    office: "town-rep",
    party: "台灣民眾黨",
    status: "nominated",
    candidacySource:
      "https://www.tpp.org.tw/election2026/candidatedetail.php?cid=225",
    nicknames: [{ name: "竹北瑞隊長", kind: "creative" }],
    news: {
      title: "民眾黨公布竹北市民代表提名",
      summary: "民眾黨 2026 年提名公告收錄林瑞德，參選竹北市第一選區市民代表。",
      url: "https://donation.tpp.org.tw/newsdetail/4533",
      date: "2026",
    },
    meme: "市民代表新手村，準備開始闖關。",
    color: "#20bec5",
    image: image("lin"),
    updated,
  },
  {
    id: "luo",
    name: "羅方妏",
    county: "臺中市",
    district: "和平區第三選區",
    office: "indigenous-rep",
    party: "無黨籍",
    status: "registered",
    candidacySource: "https://web.cec.gov.tw/tcec/article/64644",
    nicknames: [{ name: "山城新手玩家", kind: "creative" }],
    news: {
      title: "25 歲羅方妏投入和平區代表選舉",
      summary:
        "2026 年 7 月，聯合報報導羅方妏投入和平區第三選區代表選舉；9 月選委會正式登記表已列入她的姓名。",
      url: "https://udn.com/news/story/7325/9599870",
      date: "2026-07-01",
    },
    meme: "別人 25 歲打副本，我打開區代表任務。",
    color: "#da9f48",
    image: image("luo"),
    updated,
  },
];
